apiVersion: apps/v1
kind: Deployment
metadata:
  name: essential-protege
  namespace: essential
  labels:
    app.kubernetes.io/name: essential-protege
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: essential-protege
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: essential-protege
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: essential-protege
          image: docker.io/eldarrin/essential-protege:latest
          imagePullPolicy: Always
          env:
            - name: HOST_URL
              value: "flibble"
          ports:
            - name: rmi
              containerPort: 31100
              protocol: TCP
            - name: protege
              containerPort: 31200
              protocol: TCP
