apiVersion: apps/v1
kind: Deployment
metadata:
  name: essential-import
  namespace: essential
  labels:
    app.kubernetes.io/name: essential-import
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: essential-import
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: essential-import
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: essential-import
          image: docker.io/eldarrin/essential-import:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8181
              protocol: TCP
